spring:
  application:
    name: greeting-service

  profiles:
    active:
      - local

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

