spring:
  application:
    name: greeting-service
    
greeting-service:
  greeting: "Hola amigo"
  default-value: "Mundo"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

